services:
  # Base de Datos para Product Service
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-db:
    image: postgres:15-alpine
    container_name: order-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order_db
    ports:
      - "5432:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  # Identity Provider (Seguridad)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080" # Mapeado al 8081 para no chocar con el Gateway (8080)

  # Interfaz gráfica para PostgreSQL (Opcional, útil para debug)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - product-db
      - order-db

volumes:
  postgres_data:
  order_data:
