services:
  # Base de Datos para Product Service
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: ${DB_NAME_PRODUCT:-product_db}
      POSTGRES_USER: ${DB_USER_PRODUCT:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PRODUCT:-admin}
    ports:
      - "${DB_PORT_PRODUCT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Datos para Order Service
  order-db:
    image: postgres:15-alpine
    container_name: order_db
    environment:
      POSTGRES_DB: ${DB_NAME_ORDER:-order_db}
      POSTGRES_USER: ${DB_USER_ORDER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ORDER:-admin}
    ports:
      - "${DB_PORT_ORDER:-5432}:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  # Identity Provider (Seguridad)
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8081:8080" # Mapeado al 8081 para no chocar con el Gateway (8080)

  # Interfaz gráfica para PostgreSQL (Opcional, útil para debug)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - product-db
      - order-db

volumes:
  postgres_data:
  order_data:
