# 📑 Global ConfigMap (Fase 2: Contrato de Infraestructura)
# ==========================================================
# Este archivo define las configuraciones compartidas de texto plano (No sensibles)
# para el ecosistema completo del E-commerce.
# Estándar 2026: Delegación completa a K8s ETCD. Sustituye al Spring Cloud Config.

apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  labels:
    part-of: ecommerce-platform
data:
  # General
  SPRING_PROFILES_ACTIVE: prod
  
  # URLs Bases de Datos Inter-Clúster (DNS Nativo de K8s)
  DB_HOST_PRODUCT: product-db
  DB_HOST_ORDER: order-db
  DB_HOST_INVENTORY: inventory-db
  
  # Eureka (Si se usa en paralelo, de lo contrario se comenta)
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  
  # Kafka Brokers
  KAFKA_BOOTSTRAP_SERVERS: kafka:29092
