server:
  port: 8083 # Evitamos conflicto con Gateway (8080) y Config Server (8888) y Product (8082) y Discovery Server (8761)

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  # Seguridad Oauth2 (Resource Server)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/cloudnative-ecommerce

  # Database Migrations (Flyway)
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Base de Datos (Docker)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_ORDER:5432}/${DB_NAME_ORDER:order_db}
    username: ${DB_USER_ORDER:admin}
    password: ${DB_PASSWORD_ORDER:admin}
    driver-class-name: org.postgresql.Driver
    # SSL se puede configurar aquí si es necesario (ej: url: ...?ssl=${DB_SSL_ORDER:false})

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate # Estándar profesional para producción: validate en lugar de auto-generar (comportamiento por defecto -> update (es una mala practica pero se puede usar en local))
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Virtual Threads (Java 21)
  threads:
    virtual:
      enabled: true
 
  # Kafka Config
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.cloudnative.ecommerce.*"
        spring.json.use.type.headers: false
        isolation.level: read_committed
    producer:
      transaction-id-prefix: tx-order-

  # Feign Circuit Breaker (Resilience4j)
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false # Deshabilitado para usar solo @CircuitBreaker en el Adaptador (limpieza de logs)
      client:
        config:
          default:
            connectTimeout: 2000 # 2 segundos máximo para conectar
            readTimeout: 2000    # 2 segundos máximo esperando respuesta

# Configuracion de Resilience4j 
resilience4j:
  circuitbreaker:
    instances:
      productService:   # Nombre de la instancia que usaremos en la anotacion
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10              # Evalua los ultimos 10 llamados
        minimumNumberOfCalls: 5            # Necesita 5 peticiones minimo para calular la tasa de fallo
        failureRateThreshold: 50           # Si el 50% falla, el circuito se ABRE
        waitDurationInOpenState: 10s       # Tiempo de espera antes de probar de nuevo (Half-Open)
        permittedNumberOfCallsInHalfOpenState: 3 # Llamados permitidos en estado Half-Open
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - io.github.resilience4j.bulkhead.BulkheadFullException
          - feign.FeignException.NotFound

  retry:
    instances:
      productService:   # Debe coincidir con el nombre usado en CircuitBreaker
        maxAttempts: 3                     # Reintenta un total de 3 veces
        waitDuration: 2s                   # Espera 2 segundos entre reintentos
        retryExceptions:
          - feign.RetryableException       # Errores provocados por Timeout nativo de Feign
          - java.net.ConnectException      # Errores de red si el servicio está apagado
          - java.util.concurrent.TimeoutException
          - java.io.IOException

  ratelimiter:
    instances:
      productService:
        limitForPeriod: 50
        limitRefreshPeriod: 10s
        timeoutDuration: 0s

  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 20
        maxWaitDuration: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
