server:
  port: 8082 # Evitamos conflicto con Gateway (8080) y Config Server (8888)

spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  # Base de Datos (Docker)
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # ¡Cuidado en prod! Para desarrollo está bien
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[dialect]": org.hibernate.dialect.PostgreSQLDialect

  # Virtual Threads (Java 21)
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
